package cards.enumsCards;

/**
 * Describe all bonuses on cards
 *
 * Created by sserdiuk on 7/3/17.
 */
public enum BonusesInCards {
    IGNORE_ARMOR_ATTACK_ENEMY,
    FREEZE_ENEMY,
    POISON_ENEMY,
    CURSE_ENEMY,
    DISARM_ENEMY,
    RESOURCE_TAKE_OFF_ENEMY,
    STEEL_RESOURCE_ENEMY,
    DESTROY_TEMPLE_ENEMY,

    ARMOR_DECRASE_ENEMY,
    attackBonusMySelf,
    DEFENSE_BONUS_MY_SELF,
    DISPEL_MY_SELF,
    BUILD_TEMPLE_MY_SELF,
    ADD_RESOURCE_MY_SELF,
    REGENERATION_MY_SELF,
    INCREASE_HEALTH,

    DESTROY_TEMPL_FOR_ALL,
    ADD_RESOURCES_FOR_ALL,
    ADD_ARMOR_FOR_ALL,
    DESTROY_ARMOR_FOR_ALL,
    IMPLROVE_ATTACK_FOR_ALL
}
